name: publish

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodejs: [12, 14]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.nodejs }}

    - run: npm install
    - run: npm add -D esbuild
    - run: npm test
    - run: npm run-script lint
    - run: npm run-script build-all

  publish:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run-script build-all && npm run-script postbuild
      - run: npm publish dist --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
